# Generated by Django 6.0.5 on 2026-05-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('institution_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('company_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(help_text='Use bullet points separated by newlines')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Talha Abbas', max_length=100)),
                ('title', models.CharField(default='Full-Stack Engineer & AI Developer', max_length=200)),
                ('tagline', models.CharField(default='I Build Systems That Scale', help_text='Hero section main heading', max_length=300)),
                ('subtitle', models.TextField(default='Engineering premium digital experiences with cutting-edge technology.', help_text='Hero section subtitle')),
                ('bio', models.TextField(blank=True, help_text='Short bio for About preview section')),
                ('detailed_bio', models.TextField(blank=True, help_text='Extended bio for the About page')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume_file', models.FileField(blank=True, help_text='Downloadable CV/Resume PDF', null=True, upload_to='resume/')),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('email', models.EmailField(default='contact@talhaabbas.dev', max_length=254)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description for home page', max_length=300)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('years_experience', models.PositiveIntegerField(default=3)),
                ('projects_completed', models.PositiveIntegerField(default=10)),
                ('technologies_used', models.PositiveIntegerField(default=20)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('devops', 'DevOps'), ('ml', 'Machine Learning'), ('tools', 'Tools & Other')], max_length=20)),
                ('proficiency', models.PositiveIntegerField(default=80, help_text='Proficiency percentage (0-100)')),
                ('icon_class', models.CharField(blank=True, help_text='CSS icon class or SVG icon name', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in the featured skills section')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['order', 'name'],
            },
        ),
    ]
