# Generated by Django 6.0.5 on 2026-06-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_portfolio_content_refresh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='tagline',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_title_line1',
            field=models.CharField(default='I build things that', help_text='Hero section main heading (first line, normal text)', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_title_line2',
            field=models.CharField(default='actually work.', help_text='Hero section main heading (second line, gradient text)', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='subtitle',
            field=models.TextField(default='<strong style="color: var(--text-primary); font-weight: var(--fw-medium);">Software Engineer</strong> — I build complete applications that solve real problems. From writing the core logic to integrating AI, I focus on making software that is reliable and actually gets the job done.', help_text='Hero section subtitle (HTML allowed)'),
        ),
    ]
