# Generated by Django 6.0.5 on 2026-06-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_siteconfiguration_tagline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_subtitle_prefix',
            field=models.CharField(default='Software Engineer', help_text='Bold prefix text before the subtitle', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='subtitle',
            field=models.TextField(default='— I build complete applications that solve real problems. From writing the core logic to integrating AI, I focus on making software that is reliable and actually gets the job done.', help_text='Main paragraph for hero section'),
        ),
    ]
