# Generated by Django 6.0.5 on 2026-07-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_update_django_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('backend', 'Backend Engineering'), ('ai', 'AI Engineering'), ('cloud', 'Cloud & DevOps'), ('database', 'Databases & Storage'), ('languages', 'Core Languages'), ('frontend', 'Frontend & UI')], max_length=20),
        ),
    ]
